- hosts: docker
  become: true

  tasks:
  - name: 1 upload docker-compose 
    copy:
      src: "docker/docker-compose.yml"
      dest: /root/docker

  - name: 1 start container 
    shell: | 
      cd /root/docker
      docker-compose up -d

  - name: check container start
    shell: docker ps
    register: docker_is_start

  - name: print 
    debug:
      msg: "{{ docker_is_start.stdout }}"

  - name: Stop a container
    docker_container:
      name: nginx
      state: stopped

  - name: remove container
    docker_container:
      name: nginx
      state: absent

  - name: check container start
    shell: docker ps
    register: docker_is_start

  - name: print 
    debug:
      msg: "{{ docker_is_start.stdout }}"